backupninja 1.2.1

diff --git a/files/backupninja b/files/backupninja
--- a/files/backupninja
+++ b/files/backupninja
@@ -186,7 +186,7 @@ function tolower() {
 
 # simple to integer function
 function toint() {
-   echo "$1" | tr -d '[:alpha:]'
+   echo "$1" | /bin/sed 's/[^0-9]//g;s/^0\+//'
 }
 
 #
@@ -202,7 +202,7 @@ function toint() {
 # we grab the current time once, since processing
 # all the configs might take more than an hour.
 nowtime=`LC_ALL=C date +%H`
-nowday=`LC_ALL=C date +%d`
+nowday=`LC_ALL=C date +%-d`
 nowdayofweek=`LC_ALL=C date +%A`
 nowdayofweek=`tolower "$nowdayofweek"`
 
@@ -226,7 +226,7 @@ function isnow() {
        if [ "$whendayofweek" != "$nowdayofweek" ]; then
            whendayofweek=${whendayofweek%s}
            if [ "$whendayofweek" != "$nowdayofweek" ]; then
-               if [ "$whendayofweek" != "mondays" -a "$whendayofweek" != "tuesdays" -a "$whendayofweek" != "wednesdays" -a "$whendayofweek" != "thursdays" -a "$whendayofweek" != "fridays" -a "$whendayofweek" != "saturdays" -a "$whendayofweek" != "sundays" ]; then
+               if [ "$whendayofweek" != "monday" -a "$whendayofweek" != "tuesday" -a "$whendayofweek" != "wednesday" -a "$whendayofweek" != "thursday" -a "$whendayofweek" != "friday" -a "$whendayofweek" != "saturday" -a "$whendayofweek" != "sunday" ]; then
                    warning "The day in the 'when' option in the configuration is malformed. Please read the README for examples."
                fi
                if [ "$at" != "at" ]; then
@@ -234,13 +234,13 @@ function isnow() {
                fi
                if [[ "$whentimeoriginal" != @([0-9][0-9])?(:[0-9][0-9]) ]]; then
                    warning "The time in the 'when' option in the configuration is malformed or does not exist. Please read the README for examples."
-	       fi
+               fi
                return 0
            fi
        fi
    elif [ "$whenday" != "$nowday" ]; then
        if [ "$whenday" -lt 1 -o "$whenday" -gt 31 ]; then
-	   warning "The numeric value of the day in the 'when' option in the configuration does not match a day. Please read the README for examples."
+           warning "The numeric value of the day in the 'when' option in the configuration does not match a day. Please read the README for examples."
        fi
        if [ -z "$whentime" ]; then
            warning "The 'when' variable in the configuration file is malformed. You either didn't specify the day or the time. Please read the README for eamples."
@@ -278,6 +278,7 @@ script is run hourly from cron.
 
 The following options are available:
 -h, --help           This usage message
+-V, --version        Show backupninja version number
 -d, --debug          Run in debug mode, where all log messages are
                      output to the current shell.
 -f, --conffile FILE  Use FILE for the main configuration instead
@@ -374,9 +375,9 @@ function process_action() {
                [ $debug ] && colorize "$a"
             done
          )
-         retcode=$?
-         # ^^^^^^^^ we have a problem! we can't grab the return code "$?". grrr.
+         retcode=${PIPESTATUS[0]}
          echo_debug_msg=0
+         debug "handler returned exit code $retcode"
 
       else
          # a backup is probably ongoing already, so display an error message
@@ -431,12 +432,14 @@ function process_action() {
 setupcolors
 conffile="/etc/backupninja.conf"
 loglevel=3
+version="1.2.1"
 
 ## process command line options
 
 while [ $# -ge 1 ]; do
    case $1 in
       -h|--help) usage;;
+      -V|--version) echo "backupninja $version";;
       -d|--debug) debug=1; export BACKUPNINJA_DEBUG=yes;;
       -t|--test) test=1;debug=1;;
       -n|--now) processnow=1;;
@@ -465,10 +468,9 @@ while [ $# -ge 1 ]; do
          ;;
       *)
          debug=1
-         echo "Unknown option $1"
-         fatal "Unknown option $1"
+         error "Unknown option $1"
          usage
-         exit
+         exit 3
          ;;
    esac
    shift
@@ -504,7 +506,6 @@ fi
 
 # include shared functions
 . $libdirectory/tools
-. $libdirectory/vserver
 
 setfile $conffile
 
@@ -542,10 +543,7 @@ getconf RSYNC /usr/bin/rsync
 getconf DSYNC /usr/bin/dsync
 getconf DOVEADM /usr/bin/doveadm
 getconf admingroup root
-
-# initialize vservers support
-# (get config variables and check real vservers availability)
-init_vservers nodialog
+getconf reportwrap 1000
 
 if [ ! -d "$configdirectory" ]; then
    echo "Configuration directory '$configdirectory' not found."
@@ -556,7 +554,7 @@ fi
 
 if [ "$UID" != "0" ]; then
    echo "`basename $0` can only be run as root"
-   exit 1
+   exit 3
 fi
 
 ## Process each configuration file
@@ -609,34 +607,41 @@ if [ $actions_run == 0 ]; then doit=0
 elif [ "$reportemail" == "" ]; then doit=0
 elif [ $fatals != 0 ]; then doit=1
 elif [ $errors != 0 ]; then doit=1
+elif [ $halts != 0 ]; then doit=1
 elif [ "$reportsuccess" == "yes" ]; then doit=1
 elif [ "$reportwarning" == "yes" -a $warnings != 0 ]; then doit=1
 else doit=0
 fi
 
 if [ $doit == 1 ]; then
-   debug "send report to $reportemail"
-   hostname=`hostname`
-   [ $warnings == 0 ] || subject="WARNING"
-   [ $errors == 0 ] || subject="ERROR"
-   [ $fatals == 0 ] || subject="FAILED"
+   if [ -x "$(which mail 2>/dev/null)" ]; then
+      debug "send report to $reportemail"
+      hostname=`hostname`
+      [ $warnings == 0 ] || subject="WARNING"
+      [ $errors == 0 ] || subject="ERROR"
+      [ $fatals == 0 ] || subject="FAILED"
+      [ $halts == 0 ] || subject="HALTED"
 
-   {
-      for ((i=0; i < ${#messages[@]} ; i++)); do
-         echo ${messages[$i]}
-      done
-      echo -e "$errormsg"
-      if [ "$reportspace" == "yes" ]; then
-         previous=""
-         for i in $(ls "$configdirectory"); do
-            backuploc=$(grep ^directory "$configdirectory"/"$i" | /usr/bin/awk '{print $3}')
-            if [ "$backuploc" != "$previous" -a -n "$backuploc" -a -d "$backuploc" ]; then
-               df -h "$backuploc"
-               previous="$backuploc"
-            fi
+      {
+         for ((i=0; i < ${#messages[@]} ; i++)); do
+            echo ${messages[$i]}
          done
-      fi
-   } | mail -s "backupninja: $hostname $subject" $reportemail
+         echo -e "$errormsg"
+         if [ "$reportspace" == "yes" ]; then
+            previous=""
+            for i in $(ls "$configdirectory"); do
+               backuploc=$(grep ^directory "$configdirectory"/"$i" | /usr/bin/awk '{print $3}')
+               if [ "$backuploc" != "$previous" -a -n "$backuploc" -a -d "$backuploc" ]; then
+                  df -h "$backuploc"
+                  previous="$backuploc"
+               fi
+            done
+         fi
+      } | fold -s -w "$reportwrap" | mail -s "backupninja: $hostname $subject" $reportemail
+   else
+      error "Unable to locate mail executable, email report not sent!"
+      let "errors += 1"
+   fi
 fi
 
 if [ $actions_run != 0 ]; then
@@ -647,9 +652,28 @@ if [ $actions_run != 0 ]; then
 fi
 
 if [ -n "$reporthost" ]; then
-   debug "send $logfile to $reportuser@$reporthost:$reportdirectory"
-   rsync -qt $logfile $reportuser@$reporthost:$reportdirectory
+   if [ -z "$reportuser" ] || [ -z "$reportdirectory" ]; then
+      error "Unable to send report, reportuser and reportdirectory must be specified."
+      let "errors += 1"
+   elif [ ! -x "$(which rsync 2>/dev/null)" ]; then
+      error "Unable to locate rsync executable, report could not be sent to ${reporthost}."
+      let "errors += 1"
+   else
+      info "Sending $logfile to $reportuser@$reporthost:$reportdirectory"
+      execstr="rsync -qt $logfile $reportuser@$reporthost:$reportdirectory"
+      debug $execstr
+      output=$(eval $execstr 2>&1)
+      ret=$?
+      if [ $ret -ne 0 ]; then
+         error $output
+         error "An error was encountered attempting to send report to ${reporthost}."
+         let "errors += 1"
+      fi
+   fi
 fi
+
+# unset exported envvars
+unset BACKUPNINJA_DEBUG
 
 function generate_post_data() {
   cat <<EOF
@@ -698,3 +722,10 @@ if [ -n "$ICINGA2_SERVER_ADDRESS" ] && [ $actions_run != 0 ]; then
   curl -k -s -u $ICINGA2_API_USER:$ICINGA2_API_PASSWORD -H 'Accept: application/json' -X POST "https://$ICINGA2_SERVER_ADDRESS:$ICINGA2_API_PORT/v1/actions/reschedule-check?service=${ICINGA2_HOSTNAME}!backupninja" --data "$(generate_post_reschedule)" > /dev/null
 fi
 
+# return exit code
+[ $halts == 0 ] || exit 2
+[ $fatals == 0 ] || exit 2
+[ $errors == 0 ] || exit 1
+[ "$reportwarning" == "yes" -a $warnings != 0 ] && exit 1
+
+exit 0
